/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
// // package Frames;

// // import BeanClasses.AmountDetailBean;
// // import BeanClasses.ProductsBean;
// // import BeanClasses.TransactionBean;
// // import BeanClasses.UserBean;
// // import DBmanager.DBManager;
// import com.opencsv.CSVReader;
import java.awt.Font;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;


/**
 *
 * @author Dhani
 */
public class AdminFrame extends javax.swing.JFrame {
    private Vector columnNames;

    /**
     * Creates new form AdminFrame
     */
 public AdminFrame() {
                 //SET JFRAME FULL SCREEN SIZE
          setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
         getUser();
    }

 public AdminFrame(int adminId,String name) {
                 //SET JFRAME FULL SCREEN SIZE
          setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        AdminNameLabel.setText(""+name);
         getUser();
    }
 
 
    private void getUser(){
        try{
     Vector v=DBManager.getAllUser();
System.out.println(v.elementAt(1));
  userNameComboBox.removeAllItems();

       for(int i=0; i<v.size(); i++){
             userNameComboBox.addItem(v.elementAt(i));       
       
       }
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,""+e);                 
        }
    }
    
private void updateItems(){
 try {
    
     int updateRows=0;     
     int rows=itemTable.getRowCount();
    for (int row = 0; row <rows; row++) {
       int prod_id=(int)itemTable.getValueAt(row, 0);
       String prod_name = (String) itemTable.getValueAt(row, 1);
       String barcode = (String) itemTable.getValueAt(row, 2);
       int quantity = Integer.parseInt(itemTable.getValueAt(row, 3).toString());
        int unit_price =Integer.parseInt(itemTable.getValueAt(row, 4).toString());
    //JOptionPane.showMessageDialog(this,"prod_name="+prod_name+" barcode..."+barcode+"quantity..."+quantity+"unit_price..."+unit_price);  
    if(barcode==null){
     //   int pro_id=Integer.parseInt(prod_id);
       updateRows=DBManager.updateItemsByProId(prod_id,prod_name,quantity,unit_price);
    }else
    updateRows=DBManager.updateItems(prod_name, barcode, quantity,unit_price);
    }   
       if(updateRows>0)
 JOptionPane.showMessageDialog(this,"UPDATE SUCEFULLY....");

} catch (Exception e1) {
    e1.printStackTrace();} 
}
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AdminNameLabel = new javax.swing.JLabel();
        adminImgLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        searchBarcodeTextField = new javax.swing.JTextField();
        scaneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        addItemsButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        deleteRowButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userDailyDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        sellingAmountTextField = new javax.swing.JTextField();
        userNameComboBox = new javax.swing.JComboBox();
        okButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        totalDailyAmountDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalDailyAmountTextField = new javax.swing.JTextField();
        TotalAmountButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        monthluMonthChooser = new com.toedter.calendar.JMonthChooser();
        jLabel10 = new javax.swing.JLabel();
        monthllyTextField = new javax.swing.JTextField();
        MonthlyButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        USerMenuItem = new javax.swing.JMenuItem();
        adminMenuItem = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        daiyTransaction = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        productsIdMenuItem = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin:");

        AdminNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdminNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        AdminNameLabel.setText("Name");

        adminImgLabel.setIcon(new javax.swing.ImageIcon("Picture\\Users-Administrator-icon (1).png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AdminNameLabel))
                    .addComponent(adminImgLabel))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addComponent(adminImgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(AdminNameLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Search Barcode");

        searchBarcodeTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchBarcodeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchBarcodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarcodeTextFieldActionPerformed(evt);
            }
        });

        scaneButton.setIcon(new javax.swing.ImageIcon("Picture\\Search-icon.png")); // NOI18N
        scaneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                scaneButtonMouseEntered(evt);
            }
        });
        scaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaneButtonActionPerformed(evt);
            }
        });

        itemTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Product Name", "Barcode", "Quantity", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemTable.setRowHeight(25);
        itemTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(itemTable);

        addItemsButton.setIcon(new javax.swing.ImageIcon("Picture\\Shopping-cart-insert-icon.png")); // NOI18N
        addItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addItemsButtonMouseEntered(evt);
            }
        });
        addItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemsButtonActionPerformed(evt);
            }
        });

        UpdateButton.setIcon(new javax.swing.ImageIcon("Picture\\Apps-system-software-update-icon.png")); // NOI18N
        UpdateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UpdateButtonMouseEntered(evt);
            }
        });
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ClearButton.setIcon(new javax.swing.ImageIcon("Picture\\green-document-cross-icon.png")); // NOI18N
        ClearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearButtonMouseEntered(evt);
            }
        });
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        deleteRowButton.setIcon(new javax.swing.ImageIcon("Picture\\Windows-Close-Program-icon.png")); // NOI18N
        deleteRowButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteRowButtonMouseEntered(evt);
            }
        });
        deleteRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRowButtonActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("User Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date");

        userDailyDateChooser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        userDailyDateChooser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userDailyDateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userDailyDateChooserMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userDailyDateChooserMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userDailyDateChooserMouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userDailyDateChooserMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Selling Amount ");

        sellingAmountTextField.setEditable(false);
        sellingAmountTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sellingAmountTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sellingAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellingAmountTextFieldActionPerformed(evt);
            }
        });

        userNameComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameComboBoxActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okButton.setText("Get User Amount");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sellingAmountTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userNameComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userDailyDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(okButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(userNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userDailyDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sellingAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("User Daily Amount Detail");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalDailyAmountDateChooser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Date");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Daily Amount");

        totalDailyAmountTextField.setEditable(false);
        totalDailyAmountTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalDailyAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalDailyAmountTextFieldActionPerformed(evt);
            }
        });

        TotalAmountButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalAmountButton.setText("Get Toal Amount");
        TotalAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalAmountButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalDailyAmountDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(totalDailyAmountTextField)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(TotalAmountButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalDailyAmountDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalDailyAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Total Daily Amount");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Month");

        monthllyTextField.setEditable(false);
        monthllyTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        MonthlyButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MonthlyButton.setText("Get Amount");
        MonthlyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthlyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monthllyTextField)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(monthluMonthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MonthlyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monthluMonthChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MonthlyButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthllyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Monthly Amount");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchBarcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scaneButton)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addItemsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteRowButton)))
                .addContainerGap(427, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scaneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBarcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addItemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteRowButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(277, 277, 277))))
        );

        jMenu3.setText("Create Account");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        USerMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        USerMenuItem.setText("Create Account For User");
        USerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USerMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(USerMenuItem);

        adminMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        adminMenuItem.setText("Create Account For Admin");
        adminMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(adminMenuItem);

        jMenuBar2.add(jMenu3);

        jMenu7.setText("Transaction");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        daiyTransaction.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daiyTransaction.setText("Daily Transaction");
        daiyTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daiyTransactionActionPerformed(evt);
            }
        });
        jMenu7.add(daiyTransaction);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Products Details");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        productsIdMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        productsIdMenuItem.setText("Products Without Barcode");
        productsIdMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsIdMenuItemActionPerformed(evt);
            }
        });
        jMenu8.add(productsIdMenuItem);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemsButtonActionPerformed
 int rows=itemTable.getRowCount();
  System.out.println(rows);
  addItems(rows);


    }//GEN-LAST:event_addItemsButtonActionPerformed

private void addItems(int rows){
 DateFormat df = new SimpleDateFormat("YY-MM-dd");
Calendar calobj = Calendar.getInstance();
String date=(String)df.format(calobj.getTime());
System.out.println(date);

try {
      Class.forName("com.mysql.jdbc.Driver");
    Connection   con=DriverManager.getConnection("jdbc:mysql://localhost:3306/mini_mart","root","");
  
    
    //  con.setAutoCommit(false);
    String query = "Insert into products (prod_id, prod_name, prod_barcode, prod_qty, prod_price, date) values (?,?,?,?,?,?)";
    PreparedStatement pst = con.prepareStatement(query);

    for (int row = 0; row <rows; row++) {
            String prod_id=(String)itemTable.getValueAt(row,0);
    if(prod_id==null){
        String prod_name = (String) itemTable.getValueAt(row, 1);
        String barcode = (String) itemTable.getValueAt(row, 2);   
        int quantity =Integer.parseInt(itemTable.getValueAt(row, 3).toString());
        int unit_price =Integer.parseInt(itemTable.getValueAt(row, 4).toString());
        
        pst.setInt(1,0);   
        pst.setString(2, prod_name);
        pst.setString(3, barcode);
        pst.setInt(4, quantity);
        pst.setInt(5, unit_price);
        pst.setString(6, date);
        pst.addBatch();
    }// end of if
    }// end of loop
    pst.executeBatch();
JOptionPane.showMessageDialog(this,"ITEMS INSERT SUCEFULLY....");

    //con.commit();
}catch(NumberFormatException ne){
 JOptionPane.showMessageDialog(null,"Kindly Insert Number in Qty And Unit Price Column..");   
}catch (NullPointerException e) {
    
    JOptionPane.showMessageDialog(this,"Kindly Detele Empty Rows..");

}catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this,"Error"+e);

}

 }
    
    private void scaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaneButtonActionPerformed

String search_barcode=searchBarcodeTextField.getText();
if(search_barcode.equals("")){JOptionPane.showMessageDialog(null,"Kindly Insert Item Barcode "); return;}
getDataByBarcode(search_barcode);
searchBarcodeTextField.setText("");

    }//GEN-LAST:event_scaneButtonActionPerformed
private void getDataByBarcode(String barcode){
   
        try{
           
            Vector v=DBManager.getDataByBarcode(barcode);
            if(v.isEmpty()){
               int prod_id=Integer.parseInt(barcode);
               v=DBManager.getDataByProdId(prod_id);
           }
            
            System.out.println(v.size());
           if(v.size()==0){
               JOptionPane.showMessageDialog(this,"Item Not Found...");
               return;
           }
            DefaultTableModel dm = (DefaultTableModel)itemTable.getModel();
            for(int i=0; i<v.size(); i++){
               ProductsBean bean=(ProductsBean)v.elementAt(i);
               int prod_id=bean.getProd_id();
               String prod_name=bean.getProd_name();
               String prod_barcode=bean.getProd_barcode();
               int prod_qty=bean.getProd_qty();
             //  int prod_price=bean;
               dm.addRow(new Object[]{bean.getProd_id(),bean.getProd_name(),bean.getProd_barcode(),bean.getProd_qty(), bean.getProd_price()}); 
  
            }
            
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Exception"+e);
        }
   
}
    
    private void itemTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemTableKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
           ((DefaultTableModel)itemTable.getModel()).addRow(new Vector());
        }
    }//GEN-LAST:event_itemTableKeyPressed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
         DefaultTableModel dm = (DefaultTableModel)itemTable.getModel();
while(dm.getRowCount() > 0)
{
    
   dm.removeRow(0);
}

        
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void deleteRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRowButtonActionPerformed
DefaultTableModel model = (DefaultTableModel) itemTable.getModel();
        int row=itemTable.getRowCount();
     if(row==0){
        model.setRowCount(1);
     }      
 int[] rows = itemTable.getSelectedRows();
   for(int i=0;i<rows.length;i++){
     model.removeRow(rows[i]-i);

   }
    }//GEN-LAST:event_deleteRowButtonActionPerformed

    private void searchBarcodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarcodeTextFieldActionPerformed
      String searchBarcode=searchBarcodeTextField.getText();
        getDataByBarcode(searchBarcode);
        searchBarcodeTextField.setText("");
    }//GEN-LAST:event_searchBarcodeTextFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        updateItems();
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void userDailyDateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDailyDateChooserMouseClicked
      
    }//GEN-LAST:event_userDailyDateChooserMouseClicked

    private void userDailyDateChooserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDailyDateChooserMousePressed
      
    }//GEN-LAST:event_userDailyDateChooserMousePressed

    private void userDailyDateChooserMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDailyDateChooserMouseReleased
       

    }//GEN-LAST:event_userDailyDateChooserMouseReleased

    private void userDailyDateChooserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDailyDateChooserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userDailyDateChooserMouseEntered

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
 UserBean bean=(UserBean)userNameComboBox.getSelectedItem();
 if(bean==null)return;
 if(userDailyDateChooser.getDate()==null){JOptionPane.showMessageDialog(null,"Kindly Select Date");return;}
        SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-dd");
      String date = sdf.format(userDailyDateChooser.getDate());
     getUserAmountDaily(bean.getUser_id(),date);
    }//GEN-LAST:event_okButtonActionPerformed

    private void adminMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminMenuItemActionPerformed
        CreateNewAccountFrame cn=new CreateNewAccountFrame("admin");
        cn.show();
    }//GEN-LAST:event_adminMenuItemActionPerformed

    private void USerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USerMenuItemActionPerformed
        CreateNewAccountFrame cn=new CreateNewAccountFrame();
        cn.show();
    }//GEN-LAST:event_USerMenuItemActionPerformed

    private void daiyTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daiyTransactionActionPerformed
        // TODO add your handling code here:
        DailyTransactionFrame ob=new DailyTransactionFrame();
        ob.show();
        
    }//GEN-LAST:event_daiyTransactionActionPerformed

    private void sellingAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellingAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sellingAmountTextFieldActionPerformed

    private void TotalAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalAmountButtonActionPerformed
 if(totalDailyAmountDateChooser.getDate()==null){JOptionPane.showMessageDialog(null,"Kindly Select Date");return;}
        SimpleDateFormat sdf = new SimpleDateFormat("YYY-MM-dd");
        String date = sdf.format(totalDailyAmountDateChooser.getDate());
        getDailyTotalAmount(date);
      
    }//GEN-LAST:event_TotalAmountButtonActionPerformed
private void getDailyTotalAmount(String date){
    try{
     Vector v=DBManager.getDailyTotalAmountByDate(date);
   int total_Amount=0;
            for(int i=0; i<v.size(); i++){
              AmountDetailBean bean=(AmountDetailBean)v.elementAt(i);
            total_Amount+=bean.getUser_selling_amount();
            }
            totalDailyAmountTextField.setText(""+total_Amount);
    }catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(null,""+e);
               
    }    
    
}
    private void totalDailyAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalDailyAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalDailyAmountTextFieldActionPerformed

    private void MonthlyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthlyButtonActionPerformed
 
        int month=monthluMonthChooser.getMonth();
       int year = Calendar.getInstance().get(Calendar.YEAR);   
       // increament of month because jMothchoser start from 0 Zero
       ++month;
     getAmountByMonth(month,year);
    }//GEN-LAST:event_MonthlyButtonActionPerformed

    private void addItemsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemsButtonMouseEntered
        addItemsButton.setToolTipText("Insert Items");
    }//GEN-LAST:event_addItemsButtonMouseEntered

    private void UpdateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateButtonMouseEntered
     UpdateButton.setToolTipText("Update Items");
    }//GEN-LAST:event_UpdateButtonMouseEntered

    private void ClearButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearButtonMouseEntered
ClearButton.setToolTipText("Clear Table");

    }//GEN-LAST:event_ClearButtonMouseEntered

    private void deleteRowButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRowButtonMouseEntered
deleteRowButton.setToolTipText("Detele Selected Row");
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteRowButtonMouseEntered

    private void productsIdMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsIdMenuItemActionPerformed

        ProductsFrameWithoutBarcode ob=new ProductsFrameWithoutBarcode();
        ob.setVisible(true);
    }//GEN-LAST:event_productsIdMenuItemActionPerformed

    private void userNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameComboBoxActionPerformed

    private void scaneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scaneButtonMouseEntered
      scaneButton.setToolTipText("Search Barcode");
    }//GEN-LAST:event_scaneButtonMouseEntered

    
    // this method is use for getting amount by month
    private void getAmountByMonth(int month,int year){
        try{
            Vector v=DBManager.getAmountByMonthWise(month,year);
            int total_month_Amount=0;
            for(int i=0; i<v.size(); i++){
                AmountDetailBean bean=(AmountDetailBean)v.elementAt(i);
                total_month_Amount+=bean.getUser_selling_amount();
            }
            monthllyTextField.setText(""+total_month_Amount);
            
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"getAmountByMonth()"+e);
        }
    }
    
    
    // this method is user for user daily amount detail
    private void getUserAmountDaily(int user_id ,String date){
    
      try{
        Vector v=DBManager.getUserAmountDaily(user_id,date);
        int user_sell_amount=0;
        for(int i=0; i<v.size(); i++){
         AmountDetailBean bean=(AmountDetailBean)v.elementAt(i);
         user_sell_amount+=bean.getUser_selling_amount();
        }
        sellingAmountTextField.setText(""+user_sell_amount);
    }catch(Exception e){
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,"Error="+e);
    }    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         UIManager.put("OptionPane.messageFont", new Font("Arial", Font.BOLD, 13));         

        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminNameLabel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton MonthlyButton;
    private javax.swing.JButton TotalAmountButton;
    private javax.swing.JMenuItem USerMenuItem;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton addItemsButton;
    private javax.swing.JLabel adminImgLabel;
    private javax.swing.JMenuItem adminMenuItem;
    private javax.swing.JMenuItem daiyTransaction;
    private javax.swing.JButton deleteRowButton;
    private javax.swing.JTable itemTable;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthllyTextField;
    private com.toedter.calendar.JMonthChooser monthluMonthChooser;
    private javax.swing.JButton okButton;
    private javax.swing.JMenuItem productsIdMenuItem;
    private javax.swing.JButton scaneButton;
    private javax.swing.JTextField searchBarcodeTextField;
    private javax.swing.JTextField sellingAmountTextField;
    private com.toedter.calendar.JDateChooser totalDailyAmountDateChooser;
    private javax.swing.JTextField totalDailyAmountTextField;
    private com.toedter.calendar.JDateChooser userDailyDateChooser;
    private javax.swing.JComboBox userNameComboBox;
    // End of variables declaration//GEN-END:variables
}
